//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisRowerowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class UslugiUzyte
    {
        public int id { get; set; }
        public Nullable<int> ZlecenieID { get; set; }
        public string UslugiID { get; set; }
        public Nullable<int> Ilosc { get; set; }
    
        public virtual Uslugi Uslugi { get; set; }
        public virtual Zlecenia Zlecenia { get; set; }
    }
}
