//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisRowerowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zlecenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zlecenia()
        {
            this.UslugiUzyte = new HashSet<UslugiUzyte>();
        }
    
        public int id { get; set; }
        public string PracownikID { get; set; }
        public Nullable<int> KlientID { get; set; }
        public string NazwaRoweru { get; set; }
        public System.DateTime DataPrzyjecia { get; set; }
        public Nullable<System.DateTime> DataOdbioru { get; set; }
        public Nullable<decimal> CenaNaprawy { get; set; }
        public string RodzajDokumentu { get; set; }
        public Nullable<int> MetodPlatnosciID { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual MetodPlatnosci MetodPlatnosci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UslugiUzyte> UslugiUzyte { get; set; }
    }
}
